#!/usr/bin/env node

const db =  require(__dirname + '/../src/db')
const path = require('path')
const fs = require('fs')

async function main() {
    const dir = path.normalize(__dirname + '/../files') 

    await db.sequelize.sync({force: true})

    fs.readdirSync(dir).forEach(async (filename, i) => {
        const path = `${dir}/${filename}`
        await db.File.create({
            name: `The PDF ${i}`,
            path: path,
            thumbnail: path.replace('files', 'thumbnails').concat('.thumb.png')
        })
    })
}

main()
    .then(() => console.log('Done.'))
    .catch(err => console.log(err))