#!/usr/bin/env node

const db =  require(__dirname + '/../src/db')
const path = require('path')

async function main() {
    await db.sequelize.sync({force: true})

    await db.File.create({
        name: 'Sample PDF',
        path: path.normalize(__dirname + '/../files/sample.pdf'),
        thumbnail: path.normalize(__dirname + '/../thumbnails/sample.thumb.png')
    })
}

main()
    .then(() => console.log('Done.'))
    .catch(err => console.log(err))